

set(app_SOURCES
	source/App.cpp
source/App.h
source/DebugDrawer.cpp
source/DebugDrawer.h
source/Enemy.cpp
source/Enemy.h
source/FSM.cpp
source/FSM.h
source/GameObject.cpp
source/GameObject.h
source/InputManager.cpp
source/InputManager.h
source/MTL_ModernOpenGL.cpp
source/Player.cpp
source/Player.h
source/Save.cpp
source/Save.h
source/Source.cpp
source/State.cpp
source/State.h
source/StateEdit.cpp
source/StateEdit.h
source/StateMenu.cpp
source/StateMenu.h
source/StateOption.cpp
source/StateOption.h
source/StatePause.cpp
source/StatePause.h
source/StatePlay.cpp
source/StatePlay.h
	)
